import type { Metadata } from 'next';
import './globals.css';
import { Ubuntu } from 'next/font/google';
import { ToastContainer } from 'react-toastify';

const ubuntu = Ubuntu({
   weight: ['400', '500', '700'],
   subsets: ['latin'],
});

export const metadata: Metadata = {
   title: 'SoftPet',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html
         lang='en'
         className={ubuntu.className}>
         <body>
            <ToastContainer />
            {children}
         </body>
      </html>
   );
}
